### ISSUE TITLE
[Bug] 有评论的的段落无法选中一部分复制

### ISSUE THREAD

**Issue by ikkz** [OI-wiki/feedback-sys#103]
鼠标抬起之后自动 focus 到回复评论了

**Comment by Enter-tainer** [comment]
@ikkz 目前倒是可以在自动focus后，再次重复选中复制的操作，就可以复制到内容？

**Comment by ikkz** [comment]
@Enter-tainer 是的，不过感觉体验不是很好

**Comment by Enter-tainer** [comment]
看了下飞书的行为，选中被高亮的区间后，对应的评论会被高亮。但是不会focus到评论的textarea里面，选择的区间也不会丢失

**Comment by Enter-tainer** [comment]
> 目前倒是可以在自动focus后，再次重复选中复制的操作，就可以复制到内容？

试了一下似乎不太行，现在会抢焦点。我猜可以把自动focus textarea去掉，就没问题了？

**Comment by ikkz** [comment]
> > 目前倒是可以在自动focus后，再次重复选中复制的操作，就可以复制到内容？
> 
> 试了一下似乎不太行，现在会抢焦点。我猜可以把自动focus textarea去掉，就没问题了？

我觉得可以，点击已有的评论没必要自动 focus

**Comment by Enter-tainer** [comment]
https://github.com/OI-wiki/feedback-sys/blob/master/frontend/lib/main.ts#L323

我猜把这句话去掉就可以了

**Comment by shaokeyibb** [comment]
> https://github.com/OI-wiki/feedback-sys/blob/master/frontend/lib/main.ts#L323
> 
> 我猜把这句话去掉就可以了

可能还是需要做一些改动，这个 focus 是为了能确保用户打开评论窗口的时候跳转到指定评论组的位置

**Comment by ikkz** [comment]
这里好像已经跳过去了

https://github.com/OI-wiki/feedback-sys/blob/c7147e54ea10cff1997a4ef1fef53886407aed14/frontend/lib/main.ts#L316-L319

**Comment by shaokeyibb** [comment]
> 这里好像已经跳过去了
> 
> https://github.com/OI-wiki/feedback-sys/blob/c7147e54ea10cff1997a4ef1fef53886407aed14/frontend/lib/main.ts#L316-L319

（这里是跳转到指定评论组的文本框上，实际上是必要的，因为用户点击那个「添加评论」按钮的语义应该就是跳转到这个文本框

**Comment by ikkz** [comment]
点击右边的评论按钮那确实是必要的。如果我想选中一段文本来复制，然后鼠标抬起之后也是走到这里的逻辑吗

**Comment by shaokeyibb** [comment]
> 点击右边的评论按钮那确实是必要的。如果我想选中一段文本来复制，然后鼠标抬起之后也是走到这里的逻辑吗

理论上不会，这个我其实有考虑是不是浏览器会自动跳转到 focus 的元素上而不是代码执行导致的

**Comment by Enter-tainer** [comment]
但是实际上似乎还是会的？
