### ISSUE TITLE
怎么好像镜像网站没有评论？

### ISSUE THREAD

**Issue by asdf123asdf123asdf123** [OI-wiki/feedback-sys#104]
怎么好像镜像网站没有评论？

**Comment by Enter-tainer** [comment]
你用的哪个镜像呢？目前feedback sys只对“官方镜像”开放

**Comment by shaokeyibb** [comment]
除此之外，部分镜像网站因为未通过标准构建方案构建项目，因此可能不包含 feedback-sys

**Comment by asdf123asdf123asdf123** [comment]
我用的 oi.wiki……方便输入……

**Comment by Enter-tainer** [comment]
cc @Menci 似乎有一些特殊的构建逻辑

**Comment by Menci** [comment]
@asdf123asdf123asdf123 是我在维护，好久没注意了，是哪个页面有问题呢，可以截个图对比一下嘛
