### ISSUE TITLE
Double confirm when deleting comments

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/feedback-sys#128]
目前 增/改操作都是有后悔药的（发出去之后可以删除，修改点错了可以取消）但是删除一旦误触了就真的删掉了。可能可以怎么加一个确认的操作

**Comment by shaokeyibb** [comment]
可以考虑加一个确认删除的 tooltip？

**Comment by Enter-tainer** [comment]
是的。因为现在删除和其他的按钮离得很近，这几个按钮本身又比较小，感觉是有必要提供一个double check的功能

**Comment by shaokeyibb** [comment]
我节后来搞一下吧，预计改成点一下删除按钮后，替换原来发送/取消按钮为确认删除/取消
