### ISSUE TITLE
鼠标移动至部分段落会导致页面异常移位

### ISSUE THREAD

**Issue by alphagocc** [OI-wiki/feedback-sys#18]
https://github.com/user-attachments/assets/c8ff5e5f-09a3-4310-af84-6c4c17910325

**Comment by ksyx** [comment]
感觉弹出了评论列表之后再显示评论按钮干扰会少一点

**Comment by shaokeyibb** [comment]
这个原因是那个地方是个块盒（`display: block`），然后在那里 append 一个评论按钮就会导致这个问题。目前没有想到比较好的显示方案，如果放到最后一段话的右边的话会被右边的目录挡住

**Comment by shaokeyibb** [comment]
> 感觉弹出了评论列表之后再显示评论按钮干扰会少一点

这样的话似乎从用户操作的角度上不太友好？而且会导致这个功能不是很明显（

**Comment by Enter-tainer** [comment]
有一个思路，让按钮变成一个浮动的东西，叠在现有的东西上面，而不是在文档flow的内部

**Comment by shaokeyibb** [comment]
> 有一个思路，让按钮变成一个浮动的东西，叠在现有的东西上面，而不是在文档flow的内部

感觉不太好控制叠在哪里，很容易跟现有内容冲突
