### ISSUE TITLE
深色模式下不宜使用黄色作为强调色，会导致链接看不清

### ISSUE THREAD

**Issue by alphagocc** [OI-wiki/feedback-sys#19]
![image](https://github.com/user-attachments/assets/6696b78f-473d-4f55-a031-231a04dd4b9c)

**Comment by shaokeyibb** [comment]
ummmm... 会看不清吗，我感觉还好？
其实我有试很多种颜色，目前这个淡黄色在深色模式下效果其实相对还行。
可以接下来再看看有没有别的选择

**Comment by Enter-tainer** [comment]
似乎暗色模式下，这个黄色的overlay会显得比较白。。？maybe可以考虑去抄一下其他暗色的网站的颜色是怎么选的

**Comment by shaokeyibb** [comment]
草，这个是刻意变成这么白的，如果还沿用原来浅色模式的那个黄色的话会很扎眼（
