### ISSUE TITLE
一些显示问题

### ISSUE THREAD

**Issue by ksyx** [OI-wiki/feedback-sys#20]
- [ ] CSS 没有指定 [charset](https://developer.mozilla.org/zh-CN/docs/Web/CSS/@charset)
![image](https://github.com/user-attachments/assets/1f17d5fc-9cdd-4ce3-94be-23a3ae64cae3)
- [ ] 两个框的字体不一样
![image](https://github.com/user-attachments/assets/b433b43d-0007-48e7-aad7-516e96c27df5)
- [ ] 选中段落的时候下划线和背景色对比度有点低
![image](https://github.com/user-attachments/assets/774cbc75-1f76-48fd-8fe4-f3ecffcb92bc)
- [ ] Icon 没有居中对齐
![image](https://github.com/user-attachments/assets/4ec96aee-0374-4f4f-9345-c82971f640d2)
- [ ] 评论该段最好是 button 的一部分（点了可以触发新增评论
- [ ] 显示评论列表的按钮在 icon 上而不是半圆上
![image](https://github.com/user-attachments/assets/ba61817d-953e-4f7f-ab2e-50129c63f70f)
- [ ] 尝试构造了一个 offset 不合法的请求  可能前端可以过滤一下空的文本  也可以前端或者后端里维护一下合法的段
![image](https://github.com/user-attachments/assets/85e0f9dd-edbc-4714-9ef0-30ee5492f26b)

**Comment by shaokeyibb** [comment]
1. 在修了在修了
2. 没有设置字体，这个是 useragent stylesheet 的问题，我理解这个问题不大？
3. 在改了在改了
4. 这个应该是之前把 iconify-icon 换成 inline svg 导致的，一会儿看看
5. “评论该段”那块其实是他左边那个 icon 的 :after 伪元素，这么设计是保证这四个字不在文档流中，使得整个按钮不那么大，这个我稍后看看能不能通过换一个方案来解决
6. 之前提过，这个不太好改
7. 有维护合法段，目前没有过滤是因为后续可能考虑支持任意 offset 的划词评论，所以这个可能暂时不会动

**Comment by shaokeyibb** [comment]
1, 3, 4, 5 已修复，谢谢！
