### ISSUE TITLE
镜像站无法使用

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/feedback-sys#43]
可能是充实一下cors list就好？不过这个会对oauth的跳转有影响吗？

**Comment by shaokeyibb** [comment]
oauth 不会，因为跳转地址是根据访问地址决定的/

所有镜像站都要添加上吗，还是只添加 OI-Wiki 官方的部分。另外 Netlify 那个版本没有 frontend，就不用加了吧？

**Comment by Enter-tainer** [comment]
@shaokeyibb 应该所有镜像站都加。netlify不用
