### ISSUE TITLE
关于超长评论消息与 Telegram bot 转发

### ISSUE THREAD

**Issue by abc1763613206** [OI-wiki/feedback-sys#49]
ref: <https://core.telegram.org/bots/api?utm_source=botlist#:~:text=Text%20of%20the%20message%20to%20be%20sent%2C%201%2D4096%20characters%20after%20entities%20parsing>

Telegram 允许发送消息的最长长度是 4096，则目前 bot 端过长截断与前端限制评论长度至少要完成一个。

测试可见我在 <https://oi-wiki.org/intro/htc/> 发送的段落评论。

**Comment by Enter-tainer** [comment]
思考，感觉可能是tg bot这里做截断？

我不太确定要不要限制评论长度。如果要限的话，应该是要在前端和后端都要做validation
