### ISSUE TITLE
无序列表渲染存在问题

### ISSUE THREAD

**Issue by ZnPdCo** [OI-wiki/feedback-sys#71]
1. 部分无序列表鼠标移动上去下方会多出一块空白
   
   [here](https://oi-wiki.org/string/sam/#:~:text=%E7%8E%B0%E5%9C%A8%EF%BC%8C%E4%BB%BB%E5%8A%A1%E8%BD%AC%E5%8C%96%E4%B8%BA%E5%AE%9E%E7%8E%B0%E7%BB%99%E5%BD%93%E5%89%8D%E5%AD%97%E7%AC%A6%E4%B8%B2%E6%B7%BB%E5%8A%A0%E4%B8%80%E4%B8%AA%E5%AD%97%E7%AC%A6)，”现在，任务转化为实现给当前字符串添加一个字符“这一段下面的无序列表鼠标移动上去后下方会多出一块空白。 
2. 部分无序列表不会渲染
   
   [here](https://oi-wiki.org/string/sam/#%E6%AD%A3%E7%A1%AE%E6%80%A7%E8%AF%81%E6%98%8E)，正确性证明下面这一大段无序列表不会渲染评论按钮

**Comment by Enter-tainer** [comment]
1 应该是哪里的 css 写炸了

2 看了下好像是因为 这个无序列表没有被正确地注入 offset。我记得之前还有人反馈另一个页面也有部分内容没法评论的问题，可能是类似的情况

<img width="471" alt="image" src="https://github.com/user-attachments/assets/8b2b9481-7474-4f1f-a61c-4571be95968c">

**Comment by Enter-tainer** [comment]
1 似乎是因为现在会插一个div进来（而这个div可能是有高度的？）
<img width="403" alt="image" src="https://github.com/user-attachments/assets/4218cc75-2e7f-41aa-9c09-fdd772de3102">

**Comment by shaokeyibb** [comment]
> 1 似乎是因为现在会插一个div进来（而这个div可能是有高度的？） <img alt="image" width="403" src="https://private-user-images.githubusercontent.com/25521218/364692918-4218cc75-2e7f-41aa-9c09-fdd772de3102.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MjYyMzgsIm5iZiI6MTcyNTUyNTkzOCwicGF0aCI6Ii8yNTUyMTIxOC8zNjQ2OTI5MTgtNDIxOGNjNzUtMmU3Zi00MWFhLTljMDktZmRkNzcyZGUzMTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA4NDUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYzUyM2NhNmU3MzRmYmExODBkZThjZDhiMWFiMWE3YjQwMmY0MWRiNGFiZTkwMWE0YjkwODU2ZDc5ZTZkMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vUD85FldwGH3hZWU7w03Oezh9xk2dQR57EjqDn5Osi0">
> 
> F12 玩了一会没看懂是为什么

但这个 div 是 position: absolute，按理来说不会影响文档流才对。我个人可能会怀疑是这个 ul 的问题，但我目前也没搞懂为啥会这样

**Comment by shaokeyibb** [comment]
有关部分内容不会渲染的，这个是因为当某个地方的文本难以精准匹配的时候，会通过一种启发式的算法来进行匹配，但目前的匹配算法还不够完善，有时候就会导致有的元素没匹配上。这个我可能会认为是 won't fix 的

**Comment by shaokeyibb** [comment]
> > 1 似乎是因为现在会插一个div进来（而这个div可能是有高度的？） <img alt="image" width="403" src="https://private-user-images.githubusercontent.com/25521218/364692918-4218cc75-2e7f-41aa-9c09-fdd772de3102.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MjYyMzgsIm5iZiI6MTcyNTUyNTkzOCwicGF0aCI6Ii8yNTUyMTIxOC8zNjQ2OTI5MTgtNDIxOGNjNzUtMmU3Zi00MWFhLTljMDktZmRkNzcyZGUzMTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA4NDUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYzUyM2NhNmU3MzRmYmExODBkZThjZDhiMWFiMWE3YjQwMmY0MWRiNGFiZTkwMWE0YjkwODU2ZDc5ZTZkMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vUD85FldwGH3hZWU7w03Oezh9xk2dQR57EjqDn5Osi0">
> > F12 玩了一会没看懂是为什么
> 
> 但这个 div 是 position: absolute，按理来说不会影响文档流才对。我个人可能会怀疑是这个 ul 的问题，但我目前也没搞懂为啥会这样

好像是因为这个 ul 用了一个奇怪的 `display: flex-root` 布局，去掉以后就好了，我暂且蒙在鼓里

**Comment by Enter-tainer** [comment]
> 但目前的匹配算法还不够完善，有时候就会导致有的元素没匹配上。这个我可能会认为是 won't fix 的

这个最好还是能清楚为什么这里启发不出来。可能是实现上有一些bug

**Comment by Enter-tainer** [comment]
是说 display: flow root 吗？好像搜不到 flex root

**Comment by ouuan** [comment]
details 也有这个问题，而且这个布局移动会影响位于页面顶端时 navbar 的显示；有时鼠标移动布局恢复后 navbar 还未正常显示，只不过这种情况无法稳定复现

**Comment by ouuan** [comment]
它还可以导致抽搐（

https://github.com/user-attachments/assets/31940847-cbbe-4986-8b50-b165f664d6cf

**Comment by Enter-tainer** [comment]
写一下我昨天的进展：这个这个问题是因为 mkdocs material 给每一段（不知道为什么）都加了个 `display: flow-root`，这个东西的作用是，让元素的bbox变大，变到能框住里面的所有浮动元素。

因为某种原因，似乎现在的浮动评论按钮好像会在vertical的维度上超出原有的bbox，导致被hover的元素会因此变大。

有两种解决方式

1. 我们研究下为什么浮动按钮在垂直维度上会超出范围，看看能不能改掉
2. 改一改主题，把这个 display 的 css 扬了。似乎在我们这里，这个东西是没有用的？

**Comment by Enter-tainer** [comment]
![image](https://github.com/user-attachments/assets/fb7955b9-8efc-4fca-b15f-95b6203b2cf4)

似乎对details里面的代码块也有影响？hover之后，会多一个padding https://oi-wiki.org/string/sam/

**Comment by ZnPdCo** [comment]
> ![image](https://private-user-images.githubusercontent.com/25521218/365345479-fb7955b9-8efc-4fca-b15f-95b6203b2cf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2ODk5NDgsIm5iZiI6MTcyNTY4OTY0OCwicGF0aCI6Ii8yNTUyMTIxOC8zNjUzNDU0NzktZmI3OTU1YjktOGVmYy00ZmNhLWIxNWYtOTViNjIwM2IyY2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDA2MTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYTNjNTBlYzk1MzhmZGI3ZTYxMzIyZjJmYWVlNWMzZWJlYjZiYWIxNDEwZWFjZDM1NDMxOTI2YzFmN2FkZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3bcdbb922dLROC9yTOOSGtU82ffIon_6Mu58a6RHL2Q)
> 
> 似乎对details里面的代码块也有影响？hover之后，会多一个padding https://oi-wiki.org/string/sam/

是的，这一页有很多bug

**Comment by ZnPdCo** [comment]
我研究了一下，好像知道问题在哪里了。主站使用了非常多的 `last-child`，实际上这是不好的，比如我要选择 `ul li:last-child`，有以下结构：

```html
<ul>
<li></li>
<li></li>
</ul>
```

乍一看可以选择到最后一个 `li`，实际上如果加入插件后，会在最后添加一个 `div`，就选择不到了。

我的建议是，全站将 `last-child` 替换为 `last-of-type`，这样可以解决非常多的问题，上面的所有bug全部都解决了。

**Comment by Enter-tainer** [comment]
🐮啊！

话说这里的代码是维护在 mkdocs-msterial 里面吗？还是是我们自己添加的 extra css？如果是后者的话，改起来会容易很多

**Comment by ZnPdCo** [comment]
> 🐮啊！
> 
> 话说这里的代码是维护在 mkdocs-msterial 里面吗？还是是我们自己添加的 extra css？如果是后者的话，改起来会容易很多

遗憾的是，确实维护在 mkdocs-msterial 里面，需要改样式

**Comment by Enter-tainer** [comment]
@ZnPdCo 另一种手段是让feedback sys把div插入到第一个元素，这样好像可以（可以吗？）让现在的css开心？

关于mkdocs-material，这个东西似乎很久没有人动，我今天尝试build的时候遇到了一些困难。。

**Comment by ZnPdCo** [comment]
> @ZnPdCo 另一种手段是让feedback sys把div插入到第一个元素，这样好像可以（可以吗？）让现在的css开心？
> 
> 关于mkdocs-material，这个东西似乎很久没有人动，我今天尝试build的时候遇到了一些困难。。

好像不行，因为也有很多的 `first-child`，插入后会有其它的bug

**Comment by ZnPdCo** [comment]
我好像可以build成功

**Comment by Enter-tainer** [comment]
> 我好像可以build成功

cool! 您改了之后可以往 oi-wiki/mkdocs-material 里面开个 pr，我来帮您review & merge

**Comment by Enter-tainer** [comment]
> @ZnPdCo 另一种手段是让feedback sys把div插入到第一个元素，这样好像可以（可以吗？）让现在的css开心？
> 
> 关于mkdocs-material，这个东西似乎很久没有人动，我今天尝试build的时候遇到了一些困难。。

另一个想法是这里是否真的需要插一个div来显示按钮。不知道这里能不能用伪元素搞一些事情。mdn里面有一个比较类似但是不完全一样的例子：https://developer.mozilla.org/zh-CN/docs/Web/CSS/::after#%E5%B7%A5%E5%85%B7%E6%8F%90%E7%A4%BA

**Comment by shaokeyibb** [comment]
> > @ZnPdCo 另一种手段是让feedback sys把div插入到第一个元素，这样好像可以（可以吗？）让现在的css开心？
> > 关于mkdocs-material，这个东西似乎很久没有人动，我今天尝试build的时候遇到了一些困难。。
> 
> 另一个想法是这里是否真的需要插一个div来显示按钮。不知道这里能不能用伪元素搞一些事情。mdn里面有一个比较类似但是不完全一样的例子：https://developer.mozilla.org/zh-CN/docs/Web/CSS/::after#%E5%B7%A5%E5%85%B7%E6%8F%90%E7%A4%BA

我们的 div 是通过 js 创建的，伪元素可能不太适合在这里用

**Comment by Enter-tainer** [comment]
> 我们的 div 是通过 js 创建的，伪元素可能不太适合在这里用

是因为“由js创建”所以不适合伪元素吗？

我理解如果用伪元素的话，好像就不需要去用js给每个被hover的东西来查一个div了？直接在css上就可以实现了

**Comment by shaokeyibb** [comment]
> > 我们的 div 是通过 js 创建的，伪元素可能不太适合在这里用
> 
> 是因为“由js创建”所以不适合伪元素吗？
> 
> 我理解如果用伪元素的话，好像就不需要去用js给每个被hover的东西来插一个div了？直接在css上就可以实现了

ummm，其实试过，效果不太好，才变成现在这个样子。
但我具体忘了为什么不好了

**Comment by Enter-tainer** [comment]
https://github.com/OI-wiki/mkdocs-material/pull/45 @shaokeyibb 具体是怎么效果不好呀？发出来看看能不能接受？因为改mkdocs-material好像没想象的那么简单

**Comment by shaokeyibb** [comment]
> [OI-wiki/mkdocs-material#45](https://github.com/OI-wiki/mkdocs-material/pull/45) @shaokeyibb 具体是怎么效果不好呀？发出来看看能不能接受？因为改mkdocs-material好像没想象的那么简单

情况大概是这样... 目前这个模式下，整个页面共享一个 context menu 实例，会根据用户操作动态创建和移除。
如果改成 CSS 伪元素方案的话，意味着我必须为每一个段落创建一个 context menu 实例，于性能于状态管理都不是一个好的方案

**Comment by Enter-tainer** [comment]
我理解现在是一个按钮反复添加删除，伪元素会变成每个元素都自带一个按钮，根据hover情况自动显示/隐藏，会有很大区别吗

**Comment by shaokeyibb** [comment]
> 我理解现在是一个按钮反复添加删除，伪元素会变成每个元素都自带一个按钮，根据hover情况自动显示/隐藏，会有很大区别吗

ok，我突然意识到一个严重的问题是... CSS 的伪元素根本就不能被用来添加任何事件监听器... 而且用伪元素我们也完全没法拿来做一个像样的按钮

**Comment by Enter-tainer** [comment]
额好像还真没法加。。我有点理解为什么飞书会把按钮放到完全独立的另一个棵树里面了

**Comment by ZnPdCo** [comment]
> 额好像还真没法加。。我有点理解为什么飞书会把按钮放到完全独立的另一个棵树里面了

好像把按钮加到第一个元素真的能够解决问题？

**Comment by ZnPdCo** [comment]
但是我不太懂feedback-sys本地怎么调试

**Comment by shaokeyibb** [comment]
> 但是我不太懂feedback-sys本地怎么调试

README 底部有

**Comment by Enter-tainer** [comment]
> 但是我不太懂feedback-sys本地怎么调试

我能想到的办法是，先在本地build出来js和css，然后把产物移动到oi-wiki/oi-wiki里面去，覆盖掉对应的文件？ @shaokeyibb 有更好的办法吗
