### ISSUE TITLE
表格渲染出现问题

### ISSUE THREAD

**Issue by ZnPdCo** [OI-wiki/feedback-sys#72]
具体参看[这里](https://oi-wiki.org/tools/testlib/general/)的第一个表格，边框全部消失了。

**Comment by Enter-tainer** [comment]
这个是feedback sys导致的吗

**Comment by ZnPdCo** [comment]
> 这个是feedback sys导致的吗

是的，我在一个新的浏览器不进入内侧显示正常，进入就会出错

**Comment by Enter-tainer** [comment]
有点神奇。。可能是什么css打架了

**Comment by shaokeyibb** [comment]
神奇，按理来说不会，我 CSS 都是有设置前缀的

**Comment by ZnPdCo** [comment]
表格样式全部忽略掉了

**Comment by shaokeyibb** [comment]
初步感觉确实可能是 feedback-sys 的问题，关了以后就正常了

**Comment by ZnPdCo** [comment]
发现开启了之后 `.md-typeset table:not([class]) td` 就找不到了

**Comment by shaokeyibb** [comment]
> 发现开启了之后 `.md-typeset table:not([class]) td` 就找不到了

这个样式不是由 feedback-sys 提供的才对

**Comment by ZnPdCo** [comment]
> > 发现开启了之后 `.md-typeset table:not([class]) td` 就找不到了
> 
> 这个样式不是由 feedback-sys 提供的才对

我知道了，原本主题的样式就有问题

**Comment by ZnPdCo** [comment]
删去之后正常显示

**Comment by ZnPdCo** [comment]
我不太理解为什么 `table` 要加上 `:not([class])`，感觉可以直接删掉：

[table:not([class]) {](https://github.com/OI-wiki/mkdocs-material/blob/9e9affd98e8135ccf22d7c730d78d013f2141431/src/templates/assets/stylesheets/main/_typeset.scss#L445) 

把这一行改掉

**Comment by ZnPdCo** [comment]
或者说我有一个更好的解决方法，就是 feedback-sys 不要添加 class 而是添加其他属性，例如 `review_enabled=true`，然后修改一下css就行了

**Comment by shaokeyibb** [comment]
> 或者说我有一个更好的解决方法，就是 feedback-sys 不要添加 class 而是添加其他属性，例如 `review_enabled=true`，然后修改一下css就行了

也可以，比如换成 `data-review-enabled` 这种

**Comment by Enter-tainer** [comment]
看了下现在feedback sys的css，抽象做的还挺好的 如果换成 data attr 的话改起来似乎也不算麻烦

**Comment by Enter-tainer** [comment]
还有个思路就是禁止所有表格的评论

**Comment by ZnPdCo** [comment]
> 还有个思路就是禁止所有表格的评论

直接换成 data attr 吧，这样兼容性比较高

**Comment by Enter-tainer** [comment]
我发现 除了review enabled 还有 review focused

**Comment by Enter-tainer** [comment]
![image](https://github.com/user-attachments/assets/6d80aa32-b06b-4e6b-a5b3-b3febef2a477)

有个问题，这个和 on hover 有什么区别

**Comment by Enter-tainer** [comment]
额看了下好像操作classname的方法还挺多的，有 review focused/selected/has_comments

**Comment by ZnPdCo** [comment]
> 额看了下好像操作classname的方法还挺多的，有 review focused/selected/has_comments

感觉操作classname都不太好

**Comment by Enter-tainer** [comment]
> > 额看了下好像操作classname的方法还挺多的，有 review focused/selected/has_comments
> 
> 感觉操作classname都不太好

感觉本身没啥问题，只是在mkdocs这个场景，因为mkdocs-material里面会写一些傻逼的css，导致操作classname会出问题。。

**Comment by ZnPdCo** [comment]
focused有用吗，好像检查不到

**Comment by Enter-tainer** [comment]
![image](https://github.com/user-attachments/assets/d88baba9-0575-4d57-93dc-57c4c637e656)

**Comment by ZnPdCo** [comment]
我刚刚找到了，鼠标移动上去时是focused

**Comment by shaokeyibb** [comment]
![image](https://github.com/user-attachments/assets/c5033096-b600-419c-9a17-0418713ce1ec)

好消息：表格好了
坏消息：悬浮在上面现在会多一个滚动条...

**Comment by Enter-tainer** [comment]
看起来似乎是因为mkdocs会给表格外面套上几层div？这图看起来似乎悬浮按钮是在滚动条里面的😂

**Comment by Enter-tainer** [comment]
不知道这个还能不能修。。感觉如果要修的话可能就是给table写个特判？

您现在是咋改的呀，如果您已经改了attr，要不就变成 不给table注入 + 改成 data attr😂

感觉可能都行，如果能特判一下干掉好像也行。

**Comment by shaokeyibb** [comment]
> 不知道这个还能不能修。。感觉如果要修的话可能就是给table写个特判？
> 
> 您现在是咋改的呀，如果您已经改了attr，要不就变成 不给table注入 + 改成 data attr😂
> 
> 感觉可能都行，如果能特判一下干掉好像也行。

现在就是改成 data-attr，如果要做特判的话我个人觉得可能得在 content-script 那边做而不是在这边做？

**Comment by Enter-tainer** [comment]
我脑补的特判可能是在这里改的，大概是给每一个带attr的东西插入按钮的时候（或者是附近的代码）查一下它是不是table，有没有被div套起来，如果被套了就做一些事情。。。感觉丑丑的而且好像也有点脆弱。。。你是咋想的呀

**Comment by shaokeyibb** [comment]
> > 不知道这个还能不能修。。感觉如果要修的话可能就是给table写个特判？
> > 您现在是咋改的呀，如果您已经改了attr，要不就变成 不给table注入 + 改成 data attr😂
> > 感觉可能都行，如果能特判一下干掉好像也行。
> 
> 现在就是改成 data-attr，如果要做特判的话我个人觉得可能得在 content-script 那边做而不是在这边做？

我的想法是，如果要把这个库当作一个“通用”的解决方案，那就应该尽量少一些这种奇奇怪怪的特判？不然后人看起来还是屎山。

其实我们只要在 content-script 上面给 table 的父 div 上一个 `overflow: hidden` 其实就可以一定程度上修复这个问题，只不过会让按钮显示不全而已

**Comment by Enter-tainer** [comment]
okk，应该也可以。看看效果咋样吧

**Comment by Enter-tainer** [comment]
我自己觉得table 不能评论/评论起来有点bug 应该都可以接受，因为我们本身也没有很多的table

**Comment by shaokeyibb** [comment]
> okk，应该也可以。看看效果咋样吧

![image](https://github.com/user-attachments/assets/356847e9-96b3-4dfe-88d5-e85df5bcc196)

**Comment by Enter-tainer** [comment]
问题不大，冲！

**Comment by Enter-tainer** [comment]
另外我在想这个可不可以直接改 css，而不用 js

**Comment by shaokeyibb** [comment]
直接改 CSS 感觉有点侵入？目前尚不清楚这样做可能对表格带来其他的副作用

overflow: visible 好像确实可以？我一会儿做实验看看
