### ISSUE TITLE
页面卡顿

### ISSUE THREAD

**Issue by ZnPdCo** [OI-wiki/feedback-sys#74]
稍微大一点的页面就卡了，不知道为什么，按理来说只修改了css不应该会这样啊

**Comment by Enter-tainer** [comment]
![image](https://github.com/user-attachments/assets/0a6d092c-01e9-4c8e-a5d9-30191074607d)

btw 我好像又卡出来这个了

**Comment by ZnPdCo** [comment]
如果在内容少的页面之间相互切换不会出问题，内容一多就卡顿，怀疑这个bug也是卡顿造成的

**Comment by Enter-tainer** [comment]
一些测试：

- feedback sys开启时：
  - 鼠标放到右边：不卡
  - 鼠标放到正文：卡
- feedbacksys 关闭时：不卡

**Comment by ZnPdCo** [comment]
我只改了css啊？

**Comment by ZnPdCo** [comment]
也找不到 `last-of-type` 有什么效率问题

**Comment by Enter-tainer** [comment]
![image](https://github.com/user-attachments/assets/5a828e53-abd9-4c9c-b0de-c868f3e05121)

![image](https://github.com/user-attachments/assets/bff015dd-36d4-40e5-91d2-2725ecbe7103)

![image](https://github.com/user-attachments/assets/a7d5f642-1c89-454a-8eba-7e3c8331482b)

看了下是因为这个在卡。。每次 pointer in/out 的 hook 会删掉那个插进来的元素，导致计算样式需要花很长的时间？

**Comment by Enter-tainer** [comment]
截图截错了。。准确来说是这里：

![image](https://github.com/user-attachments/assets/fedf9c6e-6ecd-48f6-b1dd-cd8bcb877dc9)


```
const _closeContextMenu = () => {
  const contextMenu = document.querySelector("#review-context-menu")!;
  contextMenu.remove();
};

```

**Comment by Enter-tainer** [comment]
猜想一下。。这里动了 dom，导致那些 last type of 的 css 都需要重新计算，所以就卡了？解决方法可能是把这里变成不删除，而是隐藏（比如 display none）

**Comment by Enter-tainer** [comment]
cc @shaokeyibb 有啥想法吗

**Comment by shaokeyibb** [comment]
我的理解是，将一个元素设置为 `display: none` 依然会导致页面重绘（草好奇怪，为什么我 Google 这个有的人说会重绘有的人说不会）

**Comment by ZnPdCo** [comment]
奇怪了，我好像解决了这个问题，就是把所有的 `first-of-type` 换回去 `first-child`

**Comment by ZnPdCo** [comment]
页面就突然不卡了

**Comment by ZnPdCo** [comment]
并没有解决

**Comment by ZnPdCo** [comment]
就很奇怪，我这边页面就突然不卡顿了，强制刷新也不卡。只不过tab的bug依旧还在

**Comment by Enter-tainer** [comment]
> 就很奇怪，我这边页面就突然不卡顿了，强制刷新也不卡。只不过tab的bug依旧还在

可能是你鼠标放的位置不一样了？比如没用瞄在正文上

**Comment by ZnPdCo** [comment]
https://github.com/user-attachments/assets/7a669b66-fa68-4f6a-b98f-e29b21eda96f

**Comment by Enter-tainer** [comment]
https://github.com/user-attachments/assets/640b09ba-aec6-40a0-aee5-f589be55885d

我这里是滚轮不停地滚动，中间突然卡住的部分就是卡顿了

**Comment by ZnPdCo** [comment]
那奇了怪了，我把css文件里面的所有 `of-type` 全部换回去了依旧卡顿

**Comment by Enter-tainer** [comment]
我觉得这个问题可能是一直都存在的 只是之前没人注意到

**Comment by ZnPdCo** [comment]
> 我觉得这个问题可能是一直都存在的 只是之前没人注意到

那理论上之前应该也有tab的bug，但我一直没有触发过

**Comment by ZnPdCo** [comment]
有没有可能是

https://github.com/OI-wiki/mkdocs-material/blob/777f5cfcd3a73326494180623b704a970030df38/material/overrides/assets/javascripts/iconsearch_index.json 

这个文件的问题，这是新加入的。

因为我 build 的时候用了 `build:all`

**Comment by Enter-tainer** [comment]
tab可能是新的吧😂我是说卡顿是一直都有的问题

**Comment by Enter-tainer** [comment]
> 这个文件的问题，这是新加入的。

因为我 build 的时候用了 build:all

btw 我在本地 build:all 的时候是没这个的，但是感觉可能不是很重要就没管了。不过我觉得应该不太可能是和这个有关，您可以试着把这个删了看看会不会有什么变化

**Comment by Enter-tainer** [comment]
@Enter-tainer 可以考虑做个实验，看看如果改成display none之后，滚动还是否会卡

**Comment by shaokeyibb** [comment]
为啥我... 无论如何都不卡

**Comment by ZnPdCo** [comment]
怎么在本地测试fb-sys？

**Comment by shaokeyibb** [comment]
README 上有写，把 cloudflare-workers 和 frontend 拉起来就行了（看最后面的 `开发和测试` 单元）

**Comment by shaokeyibb** [comment]
如果你需要在 OI-Wiki 主站上测试，这个可能复杂一点，你要先部署好 OI-Wiki 主站，然后编译 frontend（顺带把 backend 地址改成你本地的），然后把编译结果手动复制粘贴到 site/assets/javascript 里

**Comment by Enter-tainer** [comment]
> 为啥我... 无论如何都不卡

你在现在主站的后缀自动机页面上试试呢。保持feedback sys是开启的状态，然后书包放在页面中间，疯狂往下一直滚动，就会一卡一卡的（就是上面那个视频

**Comment by ZnPdCo** [comment]
不太懂，如果是我想单纯在本地调试的话是需要按照后者这么做吗

**Comment by shaokeyibb** [comment]
> 不太懂，如果是我想单纯在本地调试的话是需要按照后者这么做吗

 两者都是本地调试，只不过前者拉起来的是一个单独的页面，不是 OI-Wiki 的页面

**Comment by Enter-tainer** [comment]
> 不太懂，如果是我想单纯在本地调试的话是需要按照后者这么做吗

是的，你需要先在本地跑一套主站的build流程（参考ci脚本，我猜这里post build可以不跑），然后开一个 http 服务器 serve `site` 文件夹下面的内容。

测试fb sys的话，还需要把yarn build得到的fbsys编译产物复制到主站对应的位置上（也就是 @shaokeyibb ）提到的操作

**Comment by shaokeyibb** [comment]
> > 为啥我... 无论如何都不卡
> 
> 你在现在主站的后缀自动机页面上试试呢。保持feedback sys是开启的状态，然后鼠标放在页面中间，疯狂往下一直滚动，就会一卡一卡的（就是上面那个视频

确实卡了一下，但好像不是滚动导致的，在某些地方移动鼠标就会卡（可以看出来确实是添加/一出那个按钮过程卡住的）

**Comment by ZnPdCo** [comment]
目前的发现是如果在 ul 中创建一个id为"review-context-menu"的div导航栏就会消失

**Comment by ZnPdCo** [comment]
找到了，这个样式的问题：

```css
*:has(#review-context-menu) {
  position: relative;
}
```

**Comment by ZnPdCo** [comment]
> 找到了，这个样式的问题：
> 
> ```css
> *:has(#review-context-menu) {
>   position: relative;
> }
> ```

我不太理解这个样式有什么意义

**Comment by shaokeyibb** [comment]
> > 找到了，这个样式的问题：
> > ```css
> > *:has(#review-context-menu) {
> >   position: relative;
> > }
> > ```
> 
> ~我不太理解这个样式有什么意义~
> 
> 这个样式的意思原本是不是找它的父亲？

`#review-context-menu` 依赖绝对定位来查找位置，绝对定位的坐标系依赖于其第一个 `position: relative;` 定位的父元素的坐标

**Comment by ZnPdCo** [comment]
> > > 找到了，这个样式的问题：
> > > ```css
> > > *:has(#review-context-menu) {
> > >   position: relative;
> > > }
> > > ```
> > 
> > 
> > ~我不太理解这个样式有什么意义~
> > 这个样式的意思原本是不是找它的父亲？
> 
> `#review-context-menu` 依赖绝对定位来查找位置，绝对定位的坐标系依赖于其第一个 `position: relative;` 定位的父元素的坐标

但是这个会找到它的所有祖先？

**Comment by ZnPdCo** [comment]
这不好，换一个，`*:has(> #review-context-menu)`

**Comment by ZnPdCo** [comment]
好了，我这边测试是成功了

**Comment by ZnPdCo** [comment]
这边修改了怎么push到主站？

**Comment by Enter-tainer** [comment]
push主站的事情需要发个新版，然后改主站的版本号，我或者 @shaokeyibb 来操作吧。您在这里开pr就好

**Comment by shaokeyibb** [comment]
> @Enter-tainer 可以考虑做个实验，看看如果改成display none之后，滚动还是否会卡

切换 `display: none` 确实不卡了，但是初次创建的时候还是会卡一下，如果这样的话那我可能考虑提前把所有按钮都创建好，这样可能会好一点

**Comment by Enter-tainer** [comment]
是的，感觉可能就是一次性全都创建好，然后 js 只控制显示/隐藏
