### ISSUE TITLE
鼠标hover区间优化

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/feedback-sys#79]
一个小小的体验问题，问题不是很大

![image](https://github.com/user-attachments/assets/34944a9c-fb5d-4c76-98b0-c04d5ecf62c8)

现在鼠标移动到下面的红色区域的时候，按钮会消失。

之前看过一篇文章，大概意思是说notion之类的软件为了避免这种情况，会做一些优化，就是用户hover在这个梯形区域内的时候，菜单都不会消失

**Comment by shaokeyibb** [comment]
其实我也一直有注意到这个，主要是做一个这样的遮罩不是很容易，找时间来试试看吧

**Comment by Enter-tainer** [comment]
是的，感觉不太好做，感觉有没有都行
