### ISSUE TITLE
带 HTML 锚点的评论

### ISSUE THREAD

**Issue by shaokeyibb** [OI-wiki/feedback-sys#82]
考虑允许通过锚点来指向某个特定评论并允许复制评论链接

类似于 `https://oi-wiki.org#comment-2`

同时 telegram bot 信息也可以做此适配

**Comment by Enter-tainer** [comment]
这个不知道会不会有一些坑。iirc现在评论的卡片是动态地创建出来的，可能不能依赖浏览器原生的链接锚点跳转的行为？不太清楚这里会不会有一些细节

**Comment by shaokeyibb** [comment]
> 这个不知道会不会有一些坑。iirc现在评论的卡片是动态地创建出来的，可能不能依赖浏览器原生的链接锚点跳转的行为？不太清楚这里会不会有一些细节

是，所以这里考虑用 JS 来做
