### ISSUE TITLE
优化代码评论的下划线

### ISSUE THREAD

**Issue by nicognaW** [OI-wiki/feedback-sys#85]
<img width="1004" alt="image" src="https://github.com/user-attachments/assets/a5b4df97-b354-409c-86df-d74674e579e0">

目前版本只能对一整个代码块进行评论，并且评论后会给代码块中所有字符加下划线，不太好看

**Comment by Enter-tainer** [comment]
这个可能还有点困难，您有没有什么优化的想法

**Comment by ZnPdCo** [comment]
“只能对一个代码块进行评论”是什么意思

**Comment by Enter-tainer** [comment]
> “只能对一个代码块进行评论”是什么意思

我猜这里是说，只能一次给一整个代码块评论，没法评论其中的一部分。

感觉这个限制可能还不太好去掉。具体怎么优化我还没想清楚

**Comment by Enter-tainer** [comment]
午饭评论一部分内容这个短期内应该不太好解决了，另外半截下划线的问题已经解决了
