### ISSUE TITLE
表格右边的评论按钮显示不全

### ISSUE THREAD

**Issue by ZnPdCo** [OI-wiki/feedback-sys#86]
![image](https://github.com/user-attachments/assets/c0db9cfa-de10-4ee2-bda5-3e387140a727)

主要原因是 `.md-typeset__scrollwrap` 里面有 `overflow-x: auto;`，是否需要修改主题来处理这个问题。

或者说有更好的解决方法？

**Comment by ZnPdCo** [comment]
当然，也可以改 `extra.css`

**Comment by shaokeyibb** [comment]
已提交修复，感谢！
