### ISSUE TITLE
分享按钮权限控制有误

### ISSUE THREAD

**Issue by shaokeyibb** [OI-wiki/feedback-sys#92]
分享按钮应该允许在未登录和非自己发送的评论下使用，目前和编辑/删除使用了同一套权限控制，只有管理员或自己发送的评论才可以用

**Comment by Enter-tainer** [comment]
@shaokeyibb 今天偶然看见飞书的设计，大概是hover的时候才显示编辑/删除按钮，感觉好像也还挺合理的，maybe可以偷一下

**Comment by shaokeyibb** [comment]
> @shaokeyibb 今天偶然看见飞书的设计，大概是hover的时候才显示编辑/删除按钮，感觉好像也还挺合理的，maybe可以偷一下

但是咱们目前这个情况那个按钮有可能溢出到第二行...如果加hover的话感觉有点问题吧，用户鼠标放到上面突然就换行了

**Comment by Enter-tainer** [comment]
好像也是。。有点难搞

**Comment by Enter-tainer** [comment]
噢 飞书的名字有长度限制，超长会变成省略号     text-overflow: ellipsis;

然后按钮总是在第一行，是右对齐的，hover的时候显示，有一个白色的背景，hover的时候会盖住下面的东西

**Comment by shaokeyibb** [comment]
目前做成这样：

没 hover：
![image](https://github.com/user-attachments/assets/0058ab28-0df4-43c0-aa60-a5b0bab26286)
hover：
![image](https://github.com/user-attachments/assets/48a942bf-9f1a-41e2-a85a-e41558d89ab1)

**Comment by Enter-tainer** [comment]
cool! 看起来是变成了挤压用户名的长度，也不错
